apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: shroff-data-base
  namespace: shroff-data
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deployment/Dockerfile.base
  output:
    to:
      kind: ImageStreamTag
      name: shroff-data-base:latest
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: shroff-data-base
  namespace: shroff-data
