apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shroff-data-test
  namespace: shroff-data-test
  labels:
    app: shroff-data-test
  annotations:
    haproxy.router.openshift.io/timeout: 600s
spec:
  host: shroff-data-test.int.janelia.org
  to:
    kind: Service
    name: shroff-data-test
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
