apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: shroff-data-test
  namespace: shroff-data-test
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: shroff-data-test:latest
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: shroff-data-test
  namespace: shroff-data-test
