apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shroff-data-test-anyuid
  namespace: shroff-data-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: default
    namespace: shroff-data-test
